In [1]:
# Importing Numpy
import numpy as np

In [2]:
#1. Create a null array of size 10 but the fifth value which is 1

hw1 = np.array([None,None,None,None,1,None,None,None,None,None])
print(hw1)

hw12 = np.array([None] * 10)
hw12[4]=1
print(hw12)

[None None None None 1 None None None None None]
[None None None None 1 None None None None None]


In [3]:
#2. Reverse a above created array (first element becomes last)
# Note for myself [X:Y:-1) <= from X to Y, reverse

hw2 = hw1[::-1]
print(hw2)

[None None None None None 1 None None None None]


In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
hw3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(hw3)

hw3 = np.arange(9).reshape(3, 3) 
print(hw3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

hw4 = [1,2,0,0,4,0]
print(hw4)
print(np.count_nonzero(hw4))

# return x if x is not 0, datafile
print(list(filter(lambda x: x != 0, hw4)))


SyntaxError: unexpected EOF while parsing (<ipython-input-24-e14d3692965c>, line 10)

In [6]:
#5. Create a 3x3x3 array with random values
hw5 = np.random.random(size=(3,3,3))
print(hw5)

[[[0.49233254 0.22769636 0.46707362]
  [0.05122525 0.23862167 0.34739632]
  [0.67615376 0.92362044 0.54046809]]

 [[0.26593613 0.33194084 0.04890602]
  [0.4164712  0.29770144 0.81252821]
  [0.52249267 0.12282651 0.19959171]]

 [[0.51607832 0.49294497 0.72994118]
  [0.62557138 0.23646728 0.29476981]
  [0.89038849 0.91477961 0.27760419]]]


In [7]:
#6. Create a 10x10 array with random values and find the minimum and maximum values
hw6 = np.random.random(size=(10,10))
print(hw6)
print(np.min(hw6))
print(np.max(hw6))

[[0.27005409 0.62671244 0.22440916 0.867948   0.77899486 0.08673138
  0.76150877 0.00708323 0.88323629 0.63063006]
 [0.08311346 0.77055798 0.19111007 0.98371538 0.36337456 0.64922926
  0.24253055 0.84096141 0.12059555 0.39329811]
 [0.23811443 0.03102141 0.10430772 0.04653523 0.33812774 0.19493255
  0.60163791 0.96594392 0.96278683 0.14438322]
 [0.19757802 0.69773782 0.71290804 0.53859176 0.45818602 0.29432629
  0.84823461 0.85180221 0.55966154 0.10429759]
 [0.88389065 0.11156141 0.53027363 0.49091929 0.02957805 0.83100576
  0.98118323 0.84655561 0.58413921 0.8641843 ]
 [0.3450428  0.0567083  0.37934735 0.97155779 0.21520377 0.82569601
  0.20019221 0.74118981 0.50774049 0.64343017]
 [0.19267226 0.55455507 0.33430921 0.16322821 0.41533054 0.96086776
  0.19617785 0.00823333 0.1667581  0.25757567]
 [0.90566656 0.09047074 0.04536537 0.18325103 0.79586029 0.75384138
  0.69962041 0.85606896 0.8221336  0.37614562]
 [0.88407478 0.06396285 0.6618358  0.34277469 0.67755579 0.28989403
  0.6540098 

In [8]:
#7. Create a random vector of size 30 and find the mean value
hw7 = np.random.random(size=(30,))
print(hw7)
print(np.mean(hw7))

[0.52507537 0.46212845 0.34825518 0.10135035 0.34987349 0.94285563
 0.37238878 0.98000941 0.53108975 0.39977294 0.1907064  0.85321705
 0.8390248  0.93233785 0.20016725 0.67316441 0.597892   0.01171651
 0.29372518 0.49998626 0.3167813  0.99679606 0.63344811 0.60258365
 0.60908697 0.79980042 0.63056435 0.19186962 0.16320439 0.7385591 ]
0.5262477017672742


In [9]:
#8. Create a 2d array with 1 on the border and 0 inside

hw8=np.zeros((5,5),dtype=int)
print(hw8)

hw8[:,0]=1
hw8[:,-1]=1
hw8[0,:]=1
hw8[-1,:]=1
print(hw8)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [10]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

hw91 = np.random.randint(0,10,(5,3))
hw92 = np.random.randint(0,10,(3,2))
print(hw91)
print(hw92)
hw9=hw91*hw91
print(hw9)

[[5 1 2]
 [1 3 3]
 [7 6 5]
 [4 3 9]
 [3 0 1]]
[[0 1]
 [6 2]
 [5 8]]
[[25  1  4]
 [ 1  9  9]
 [49 36 25]
 [16  9 81]
 [ 9  0  1]]


In [27]:
#10. Extract the integer part of a random array

hw10 = np.random.random(size=(3,3))+1.5
print(hw10)
print(hw10 // 1)

print(np.trunc(hw10))

[[2.01466848 1.71248848 2.07198858]
 [2.18451353 1.7435189  2.34661773]
 [2.15532863 2.28439055 2.42123343]]
[[2. 1. 2.]
 [2. 1. 2.]
 [2. 2. 2.]]
[[2. 1. 2.]
 [2. 1. 2.]
 [2. 2. 2.]]


In [12]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4
hw11 = np.random.randint(0,5,(5,5))
hw11

array([[3, 2, 1, 3, 3],
       [3, 0, 3, 1, 0],
       [2, 3, 4, 0, 1],
       [2, 2, 4, 2, 0],
       [3, 1, 1, 1, 3]])

In [13]:
#12.  Create a random vector of size 10 and sort it
hw12 = np.random.randint(1,10,(10,))
print(hw12)
hw12.sort()
print(hw12)

[5 7 8 4 3 2 1 9 2 1]
[1 1 2 2 3 4 5 7 8 9]


In [26]:
#13. Consider two random array A anb B, check if they are equal.

hw121 = np.random.randint(1,10,(3,))
hw122 = np.random.randint(1,10,(3,))
print(np.count_nonzero(hw121-hw122))

np.array_equal(hw121, hw122)

3


False

In [16]:
#14. How to tell if a given 2D array has null columns?

hw14 = np.array([[0,None,2],[3,4,None],[None,7,8]])
print (hw14)
print(list(map(lambda x: x, filter(lambda x: x == None, hw14[0,:]))))

##### QUESTION 1: If I do not include [0,:], an error shows up ==> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
# How do we solve this?

[[0 None 2]
 [3 4 None]
 [None 7 8]]
[None]


In [15]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?

hw15 = np.random.randint(0,10,(4,4))
print(hw15)
print(sum(sum(map(lambda x: x, hw15[-2:,]))))

[[9 9 5 7]
 [6 7 5 0]
 [1 1 9 7]
 [4 8 4 1]]
35


In [29]:
#16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

hw151 = np.random.randint(0,10,(5,5,3))
print(hw151)

hw152 = np.random.randint(0,10,(5,5))
print(hw152)

print(np.outer(hw151, hw152))

# below building a 3D array out of a 2D array
hw153 = np.stack([hw152, hw152, hw152, hw152, hw152])
print(hw153)

[[[8 9 7]
  [5 8 1]
  [8 2 5]
  [1 2 3]
  [8 7 9]]

 [[7 3 3]
  [1 8 3]
  [6 9 9]
  [2 1 0]
  [9 9 3]]

 [[5 1 5]
  [8 4 3]
  [7 0 6]
  [1 2 5]
  [0 6 0]]

 [[0 4 8]
  [4 8 1]
  [2 8 6]
  [8 2 2]
  [2 1 6]]

 [[3 4 5]
  [0 0 9]
  [9 1 1]
  [6 0 5]
  [7 5 7]]]
[[9 8 4 1 7]
 [3 2 2 7 6]
 [1 4 6 7 4]
 [3 8 9 3 8]
 [2 0 4 6 8]]
[[72 64 32 ... 32 48 64]
 [81 72 36 ... 36 54 72]
 [63 56 28 ... 28 42 56]
 ...
 [63 56 28 ... 28 42 56]
 [45 40 20 ... 20 30 40]
 [63 56 28 ... 28 42 56]]
[[[9 8 4 1 7]
  [3 2 2 7 6]
  [1 4 6 7 4]
  [3 8 9 3 8]
  [2 0 4 6 8]]

 [[9 8 4 1 7]
  [3 2 2 7 6]
  [1 4 6 7 4]
  [3 8 9 3 8]
  [2 0 4 6 8]]

 [[9 8 4 1 7]
  [3 2 2 7 6]
  [1 4 6 7 4]
  [3 8 9 3 8]
  [2 0 4 6 8]]

 [[9 8 4 1 7]
  [3 2 2 7 6]
  [1 4 6 7 4]
  [3 8 9 3 8]
  [2 0 4 6 8]]

 [[9 8 4 1 7]
  [3 2 2 7 6]
  [1 4 6 7 4]
  [3 8 9 3 8]
  [2 0 4 6 8]]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [37]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

hw17 = np.random.randint(0,10,(10,10))
print(hw17)

hw171 = np.stack([hw17[0:3,0:3], hw17[0:3,1:4], hw17[0:3,2:5],hw17[0:3,3:6],hw17[0:3,4:7],hw17[0:3,5:8],hw17[0:3,6:9],hw17[0:3,7:10]])
print(hw171)

##### QUESTION 3: I did the first set of columns on teh first three rows. Where should be a better way of doing this!

[[5 1 8 0 8 9 8 2 2 9]
 [4 4 4 2 8 5 6 9 3 2]
 [6 2 2 9 4 7 8 4 0 6]
 [6 2 2 1 6 8 6 9 9 6]
 [3 8 9 7 3 8 8 9 6 7]
 [7 5 8 9 9 8 1 4 7 3]
 [4 2 4 0 6 9 9 0 7 8]
 [4 1 7 3 8 0 1 4 5 6]
 [0 7 5 3 4 7 7 7 2 8]
 [8 8 9 9 3 1 3 6 0 7]]
[[[5 1 8]
  [4 4 4]
  [6 2 2]]

 [[1 8 0]
  [4 4 2]
  [2 2 9]]

 [[8 0 8]
  [4 2 8]
  [2 9 4]]

 [[0 8 9]
  [2 8 5]
  [9 4 7]]

 [[8 9 8]
  [8 5 6]
  [4 7 8]]

 [[9 8 2]
  [5 6 9]
  [7 8 4]]

 [[8 2 2]
  [6 9 3]
  [8 4 0]]

 [[2 2 9]
  [9 3 2]
  [4 0 6]]]


In [18]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

hw17 = np.random.randint(0,10,(16,16))
print(hw17)
print(sum(sum(map(lambda x: x, hw17[0:4,0:4]))))

##### QUESTION 4: I'm not sure if I understoon the question correctly...

[[6 1 1 0 1 7 7 3 4 9 8 7 2 6 9 5]
 [6 4 3 6 3 7 9 6 6 2 9 8 7 5 7 4]
 [3 6 3 0 8 8 6 8 7 8 3 3 0 0 7 3]
 [8 4 8 8 9 5 6 3 5 3 2 2 1 8 1 2]
 [9 7 0 7 9 3 9 1 1 9 2 6 8 1 4 1]
 [0 0 5 5 0 2 6 4 6 4 6 4 2 8 2 8]
 [5 3 0 4 0 5 5 3 5 4 9 9 2 4 3 8]
 [6 0 8 7 0 1 9 5 2 4 7 2 2 9 1 6]
 [1 7 1 2 0 0 9 3 7 1 9 1 6 6 3 8]
 [7 4 5 4 5 6 9 1 5 9 3 4 3 2 1 1]
 [0 0 2 8 3 4 4 3 5 4 3 6 0 6 9 4]
 [5 2 2 4 0 2 5 9 3 9 8 9 3 7 0 2]
 [1 9 2 2 8 9 6 5 1 4 0 6 4 4 8 4]
 [6 5 5 7 0 7 9 6 6 6 2 3 2 0 3 0]
 [1 4 7 1 7 2 1 7 8 2 1 7 3 8 3 8]
 [3 5 4 3 8 5 3 6 8 4 1 4 7 4 2 3]]
67


NOTE: BELOW IS USING DATA PROVIDED

In [19]:
import pandas as pd
hwdata = pd.read_csv("C:/ETSProjects_SCB/UpskillTraining_2022/Week2/Homework/sample_test_data.csv")

In [20]:
# calculate summary statistics of data provided using pandas and numpy

print(hwdata.shape)
hwdata.info()
hwdata.describe()

(476, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476 entries, 0 to 475
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   item1     476 non-null    int64 
 1   item2     476 non-null    int64 
 2   item3     476 non-null    int64 
 3   item4     476 non-null    int64 
 4   item5     476 non-null    int64 
 5   item6     476 non-null    int64 
 6   item7     476 non-null    int64 
 7   item8     476 non-null    int64 
 8   item9     476 non-null    int64 
 9   item10    476 non-null    int64 
 10  item11    476 non-null    int64 
 11  playerID  476 non-null    object
dtypes: int64(11), object(1)
memory usage: 44.8+ KB


item1       item2       item3       item4       item5       item6  \
count  476.000000  476.000000  476.000000  476.000000  476.000000  476.000000   
mean     0.640756    0.617647    1.678571    0.588235    0.936975    0.852941   
std      0.480284    0.486473    0.467516    0.492671    0.243264    0.354537   
min      0.000000    0.000000    1.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    1.000000    0.000000    1.000000    1.000000   
50%      1.000000    1.000000    2.000000    1.000000    1.000000    1.000000   
75%      1.000000    1.000000    2.000000    1.000000    1.000000    1.000000   
max      1.000000    1.000000    2.000000    1.000000    1.000000    1.000000   

            item7       item8       item9      item10      item11  
count  476.000000  476.000000  476.000000  476.000000  476.000000  
mean     0.972689    1.934874    1.426471    0.544118    0.674370  
std      0.163159    0.247008    0.726095    0.498574    0.844209  
min      0.000000    1.000000    0.000000    0.000000    0.000000  
25%      1.000000    2.000000    1.000000    0.000000    0.000000  
50%      1.000000    2.000000    2.000000    1.000000    0.000000  
75%      1.000000    2.000000    2.000000    1.000000    1.000000  
max      1.000000    2.000000    2.000000    1.000000    2.000000

In [90]:
# Below using Numpy
import numpy as np

print ('mean')
print(np.mean(hwdata,axis=0))
print ('variance')
print(np.var(hwdata,axis=0))
print ('sum')
print(np.sum(hwdata,axis=0))
print ('max')
print(np.max(hwdata,axis=0))
print ('min')
print(np.min(hwdata,axis=0))

##### QUESTION 5: Below seeing errors in percentile, I'm not sure how to fix it!
print ('percentile')
print(np.percentile(hwdata,30,axis=0))

mean
item1     0.640756
item2     0.617647
item3     1.678571
item4     0.588235
item5     0.936975
item6     0.852941
item7     0.972689
item8     1.934874
item9     1.426471
item10    0.544118
item11    0.674370
dtype: float64
variance
item1     0.230188
item2     0.236159
item3     0.218112
item4     0.242215
item5     0.059053
item6     0.125433
item7     0.026565
item8     0.060885
item9     0.526106
item10    0.248054
item11    0.711192
dtype: float64
sum
item1                                                     305
item2                                                     294
item3                                                     799
item4                                                     280
item5                                                     446
item6                                                     406
item7                                                     463
item8                                                     921
item9                                 

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [21]:
##### Question 6 = Do I have to change this into matrixes like this all the time?

hwdatamatrix = np.array(hwdata)
hwdatamatrix[:,4]

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,

In [22]:
#19. Generate 2 random gaussian distributions and run a t-test to see differences
# Comparing items 5 and 9

import scipy
from scipy import stats
stats.ttest_ind(hwdatamatrix[:,4],hwdatamatrix[:,8])

Ttest_indResult(statistic=-13.946293637388237, pvalue=2.3549546326746613e-40)